# ULPatch mkdocs.yml file
#
# $ mkdocs build
# $ mkdocs serve
#
site_name: ULPatch Documents
site_description: ULPatch is open source user space live patch tool
site_url: https://rtoax.github.io/ulpatch/
repo_url: https://github.com/Rtoax/ulpatch
repo_name: Rtoax/ulpatch
copyright: Copyright &copy; 2021 - 2025 Rong Tao

nav:
  - Home: index.md
  - Installation: INSTALL.md
  - Theory: THEORY.md
  - Tutorials:
    - Code Style: code-style.md
    - Developer: developers.md
    - Log: log.md
    - ULPatch: ulpatch.md
    - ULPInfo: ulpinfo.md
    - ULTask: ultask.md
    - ULPatchTest: ulpatch_test.md
    - Contributing: CONTRIBUTING.md
  - Knowledge:
    - Elf: elf.md
    - Relocations: relocations.md
    - Symbol Value: symbol-value.md
    - Data Structure: data-structure.md
  - Releases: RELEASE.md
  - Changelog: CHANGELOG.md
  - TODO: TODO.md

theme:
  name: material
  logo: images/logo.drawio.svg
  favicon: images/logo.drawio.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    # - navigation.instant  # see https://github.com/ultrabug/mkdocs-static-i18n/issues/62
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotations

markdown_extensions:
  # Officially Supported Extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - tables
  - toc:
      permalink: true
  - wikilinks
  # Third Party Extensions(Bundles, PyMdown Extensions)
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # Headings
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: true
            # Members
            show_submodules: false
            # Docstrings
            docstring_section_style: spacy
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
        - locale: zh
          default: false
          name: 中文
          nav_translations:
            Home: 主页
            Installation: 安装
            Theory: 原理
            Tutorials: 教程
            Code Style: 代码风格
            Developer: 开发者
            Log: 日志
            ULPatch: ULPatch用户态热补丁
            ULPInfo: ULPatch用户态热补丁查看
            ULTask: ULTask进程修改器
            ULPatchTest: ULPatch测试
            Contributing: 贡献
            Knowledge: 相关知识
            Elf: ELF文件
            Relocations: 重定向
            Symbol Value: 符号地址
            Data Structure: 数据结构
            Releases: 发布
            Changelog: 修改记录
            TODO: 未完待续

extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:rtoax@foxmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/Rtoax/ulpatch
