# SPDX-License-Identifier: GPL-2.0-or-later
FROM ubuntu:devel

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt install -y build-essential
RUN apt install -y \
	bash-completion \
	binutils-dev \
	cmake \
	gcc \
	git \
	libc6 \
	libcapstone-dev \
	libelf-dev \
	libssl-dev \
	libunwind-dev \
	util-linux

VOLUME ["/ulpatch"]
WORKDIR /ulpatch
RUN cmake -B /ulpatch/build
RUN make -C /ulpatch/build -j$(nproc)
RUN make -C /ulpatch/build install
ENTRYPOINT ["/usr/bin/ulpatch"]
