FROM ubuntu:devel

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y \
	libc6 \
	cmake \
	gcc \
	binutils-dev \
	libunwind-dev

COPY . /src
WORKDIR /src
RUN cmake -B /build
RUN make -C /build -j$(nproc)
ENTRYPOINT ["/build/src/ulpatch"]
