.TH uftrace 8  "2022-10-01" "USER COMMANDS"
.SH NAME
uftrace \- Userspace ftrace.
.SH SYNOPSIS
.B uftrace
[\fI\,OPTION\/\fR]... [\fI\,FUNCTION\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
uftrace Tracing a running process

This program is also a basic command of upatch

.SH ARGUMENTS

TODO

.SH OS
Linux
.SH STABILITY
Unstable - in development.
.SH AUTHOR
Written by Rong Tao
.SH SEE ALSO
upatch(8), utask(8)
