.TH ulftrace 8  "2022-10-01" "USER COMMANDS"
.SH NAME
ulftrace \- Userspace ftrace.
.SH SYNOPSIS
.B ulftrace
[\fI\,OPTION\/\fR]... [\fI\,FUNCTION\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
ulftrace Tracing a running process

This program is also a basic command of ULPatch.

.SH ARGUMENTS
.TP
\fB\-\-log-level\fR[=\fI\,LEVEL\/\fR], \fB\-\-lv\fR[=\fI\,LEVEL\/\fR]
Specify a log level. The LEVEL could be number(see
.BR syslog (3)
) or string(debug,dbg,info,inf,notice,note,warning,warn,error,err,crit,alert,emerg).
For example, if you want to set log level to LOG_ERR, just:
.BR --lv=error .
.TP
\fB\-\-log-debug\fR
Set log level to DEBUG.
.TP
\fB\-\-log-error\fR
Set log level to ERROR.
.TP
\fB\-u\fR, \fB\-\-dry-run\fR
Don't actually run.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show verbose information.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show version information.

TODO

.SH OS
Linux
.SH STABILITY
Unstable - in development.
.SH AUTHOR
Written by Rong Tao
.SH SEE ALSO
.BR ulpatch (8),
.BR ulpinfo (8),
.BR ultask (8),
.BR ulp-config (8)
