.TH ulp-config 8  "2024-07-20" "USER COMMANDS"
.SH NAME
ulp-config \- Print ULPatch compilation options
.SH SYNOPSIS
.B ulp-config
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
\fBulp-config\fP makes it easier to build ulpatch that use ULPatch. It  can print the  compiler flags, linker  flags  and  object  libraries  needed  to link against ULPatch.

Good output to \fBstdout\fP, Wrong output to \fBstderr\fP.

This program is also a basic command of ULPatch.

.SH ARGUMENTS
.TP
\fB\-\-cflags\fR
Print the C compiler flags needed to use ULPatch headers.
.TP
\fB\-\-ldflags\fR
Print the flags needed to link against ULPatch libraries.
.TP
\fB\-\-libs\fR
Print all the libraries needed to link against the specified ULPatch components, including any dependencies.
.TP
\fB\-\-cc\fR \fICOMPILER\fP
Specify compiler, default: \fBgcc\fP, you should specify this argument before \fB--cflags\fP.
.TP
\fB\-\-ld\fR \fILINKER\fP
Specify compiler, default: \fBld\fP, you should specify this argument before \fB--ldflags\fP and \fB--libs\fP.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help information.
.EE
.SH OS
Linux
.SH STABILITY
Unstable - in development.
.SH AUTHOR
Written by Rong Tao
.SH SEE ALSO
ulpatch(8), ulpinfo(8), ulftrace(8), ultask(8)
