.TH ulpatch 8  "2022-10-01" "USER COMMANDS"
.SH NAME
ulpatch \- Userspace livepatch.
.SH SYNOPSIS
.B ulpatch
[\fI\,OPTION\/\fR]... [\fI\,FUNCTION\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
ulpatch Patching a running process

This program is also a basic command of ulpatch

.SH ARGUMENTS

TODO

.SH OS
Linux
.SH STABILITY
Unstable - in development.
.SH AUTHOR
Written by Rong Tao
.SH SEE ALSO
uftrace(8), utask(8)
