.TH ulpatch 8  "2022-10-01" "USER COMMANDS"
.SH NAME
ulpatch \- Userspace livepatch.
.SH SYNOPSIS
.B ulpatch
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
ulpatch Patching a running process

This program is also a basic command of ulpatch

.SH ARGUMENTS
.TP
\fB\-p\fR, \fB\-\-pid\fR [PID]
Specify a target process's PID.
.TP
\fB\-\-patch\fR [ULPATCH.ELF]
Specify a ulpatch.elf file to patch to target process.

.SH OS
Linux
.SH STABILITY
Unstable - in development.
.SH AUTHOR
Written by Rong Tao
.SH SEE ALSO
ulftrace(8), ultask(8)
