#!/bin/bash
# Copyright (C) 2024-2026 Rong Tao
#
# Usage:
# $ [VC=1] [{FORCE|FC}=1] [NMOD=n] [NADD=n] [NDEL=n] git commit ...
# - VC: Verbose mode of Commit
# - FORCE/FC: Force Commit
set -e

readonly GIT_TOPDIR=$(git rev-parse --show-toplevel 2>/dev/null || :)
readonly MY_DIRECTORY=$(realpath $(dirname $(realpath $0))/../../../)

[[ -z ${FC} ]] && FC=${FORCE}

# Usage: $ NMOD=6 git commit -s
[[ -z ${NMOD} ]] && NMOD=4
[[ -z ${NADD} ]] && NADD=1
[[ -z ${NDEL} ]] && NDEL=1

if [[ ${VC} ]]; then
	set -x
fi

fatal() {
	echo >&2 -e "\033[1;31mFATAL: ${@}\033[0m"
	if [[ -z ${FC} ]]; then
		echo >&2 -e "FATAL: Try FC=1/FORCE=1"
		exit 1
	fi
}

readonly pre_scripts=(
	${MY_DIRECTORY}/scripts/clang-format.sh
	${MY_DIRECTORY}/scripts/docs/linux-reference.sh
)

for script in ${pre_scripts[@]}
do
	if [[ -e ${script} ]]; then
		${script}
	fi
done

try_add=( $(git status --short | grep ^A | awk '{print $2}' || true) )
try_del=( $(git status --short | grep ^D | awk '{print $2}' || true) )
try_modify=( $(git status --short | grep ^M | awk '{print $2}' || true) )

# Redirect output to stderr.
exec 1>&2

hint_changelog() {
	if [[ -f ${GIT_TOPDIR}/CHANGELOG.md ]] &&
	  ! [[ -L ${GIT_TOPDIR}/CHANGELOG.md ]]; then
		if ! [[ " ${try_modify[@]} " =~ " CHANGELOG.md " ]]; then
			git status --short
			fatal "${@}" "you forgot modify CHANGELOG!!!"
		fi
	fi
	if [[ -f ${GIT_TOPDIR}/docs/CHANGELOG.md ]]; then
		if ! [[ " ${try_modify[@]} " =~ " docs/CHANGELOG.md " ]]; then
			git status --short
			fatal "${@}" "you forgot modify docs/CHANGELOG!!!"
		fi
	fi
	if [[ -f ${GIT_TOPDIR}/docs/en/CHANGELOG.md ]]; then
		if [[ ! " ${try_modify[@]} " =~ " docs/en/CHANGELOG.md " ]] ||
		   [[ ! " ${try_modify[@]} " =~ " docs/zh/CHANGELOG.md " ]]; then
			git status --short
			fatal "${@}" "you forgot modify docs/{en,zh}/CHANGELOG.md!!!"
		fi
	fi
}

docs_check() {
	if [[ ! -d ${GIT_TOPDIR}/Documentation ]]; then
		return 0
	fi

	# Detect documentation changed
	if [[ " ${try_modify[@]} " =~ "Documentation" ]] ||
	   [[ " ${try_add[@]} " =~ "Documentation" ]] ||
	   [[ " ${try_del[@]} " =~ "Documentation" ]]; then
		# Not found version field is changed.
		if [[ ! " ${try_modify[@]} " =~ " Documentation/conf.py " ]] ||
		   [[ "$(git diff --staged ${GIT_TOPDIR}/Documentation/conf.py | \
				grep -o ^+version)" != "+version" ]]; then
			fatal "You need to change doc version in Documentation/conf.py"
		fi
	fi

	if [[ " ${try_modify[@]} " =~ "README.md" ]] ||
	   [[ " ${try_add[@]} " =~ "README.md" ]]; then
		fatal "Don't modify/add README.md, please move it to Documentation!"
	fi
}

broken_symlinks=( $(find ${GIT_TOPDIR} -xtype l) )
if [[ ${#broken_symlinks[@]} -ge 1 ]]; then
	fatal "Broken-symlink: ${broken_symlinks[@]}"
fi

for f in ${try_add[@]}
do
	[[ -d ${f} ]] && continue

	# true: for empty file
	read -r -N 8 bin < $f || true
	if [[ $bin == $'\x7f'ELF* ]]; then
		fatal "You are trying to add <$f> ELF file to git-tree, see git status."
	# ar file start from "!<arch>\n", see /usr/include/ar.h
	elif [[ $bin == $'!<arch>\n' ]]; then
		fatal "You are trying to add <$f> ar file to git-tree, see git status."
	elif [[ $bin == $'gmon'* ]]; then
		fatal "You are trying to add <$f> GNU prof performance file to git-tree, see git status."
	fi
	if [[ $(basename $f) == vmlinux.h ]]; then
		fatal "vmlinux.h is too big, generate it with bpftool command!!!"
	fi
	if [[ "$(file $f) " =~ ": data " ]] && [[ -z ${FC} ]]; then
		fatal "$f is considered a data file, forbidden to commit!!!"
	fi
done

# modify,add,delete files, need modify CHANGELOG.md too
[[ ${#try_modify[@]} -ge ${NMOD} ]] && hint_changelog "<Modify too many files: ${try_modify[@]}, try NMOD=100>"
[[ ${#try_del[@]} -ge ${NDEL} ]] && hint_changelog "<Delete files: ${try_del[@]}, try NDEL=100>"
[[ ${#try_add[@]} -ge ${NADD} ]] && hint_changelog "<Add files: ${try_add[@]}, try NADD=100>"

docs_check

exit 0
