#!/bin/bash
# Copyright (C) 2024 Rong Tao
#
set -e

readonly ANSI_BOLD="\033[1m"
readonly ANSI_GRAY="\033[2m"
readonly ANSI_UNDERLINE="\033[4m"
readonly ANSI_RESET="\033[m"

CC=gcc
LD=ld

already_run=
run_cflags=
run_libs=
run_ldflags=
declare -a cflags libs ldflags


__usage__()
{
	echo -e "
${ANSI_BOLD}NAME${ANSI_RESET}
    ulp-config - Print ULPatch compilation options

${ANSI_BOLD}SYNOPSIS${ANSI_RESET}
    ${ANSI_BOLD}ulp-config${ANSI_RESET} [${ANSI_UNDERLINE}options${ANSI_RESET}]

${ANSI_BOLD}DESCRIPTION${ANSI_RESET}
    ulp-config makes it easier to build ulpatch that use ULPatch. It  can print
    the  compiler flags, linker  flags  and  object  libraries  needed  to link
    against ULPatch.

${ANSI_BOLD}ARGUMENT${ANSI_RESET}

   --cflags           Print the C compiler flags needed to use ULPatch headers.

   --ldflags          Print the flags needed to link against ULPatch libraries.

   --libs             Print all the libraries needed to link against the speci-
                      fied ULPatch components, including any dependencies.

   --cc [COMPILER]    Specify compiler, default: ${CC}, you should specify this
                      argument before --cflags.

   --ld [LINKER]      Specify linker, default: ${LD}, you should specify this
                      argument before --ldflags and --libs.

   -h, --help         show this help information

${ANSI_BOLD}SEE ALSO${ANSI_RESET}
   ulpinfo(8), ulftrace(8), ultask(8), ulp-config(8)

" >&2

	exit ${1-0}
}

goodbye()
{
	local ret=$?
}

trap "goodbye" EXIT

set_ld()
{
	LD=$1
	${LD} --help 2>&1 >/dev/null || {
		echo "ERROR: Bad ${LD}" >&2
		exit 1
	}
}

set_cc()
{
	CC=$1
	${CC} --help 2>&1 >/dev/null || {
		echo "ERROR: Bad ${CC}" >&2
		exit 1
	}
}

print_cflags()
{
	cflags+=( "-I/usr/include/" )
	cflags+=( "-D_GNU_SOURCE" )
	echo -n ${cflags[@]}
}

print_ldflags()
{
	ldflags+=( "-relocatable" )
	ldflags+=( "--build-id=sha1" )
	ldflags+=( "-z noexecstack" )

	if [[ "$(${LD} --help | grep no-warn-rwx-segments 2>/dev/null || true)" ]]; then
		ldflags+=( "--no-warn-rwx-segments" )
	fi

	echo -n ${ldflags[@]}
}

print_libs()
{
	echo -n ${libs[@]}
}

TEMP=$(getopt \
	--options h \
	--long cc: \
	--long ld: \
	--long cflags \
	--long ldflags \
	--long libs \
	--long help \
	-n ulp-config -- "$@")

test $? != 0 && __usage__ 1

eval set -- "$TEMP"

while true; do
	case $1 in
	--cflags)
		shift
		already_run=YES
		run_cflags=YES
		;;
	--ldflags)
		shift
		already_run=YES
		run_ldflags=YES
		;;
	--libs)
		shift
		already_run=YES
		run_libs=YES
		;;
	--cc)
		shift
		set_cc $1
		shift
		;;
	--ld)
		shift
		set_ld $1
		shift
		;;
	-h|--help)
		shift
		__usage__
		;;
	--)
		shift
		break
		;;
	esac
done

if [[ -z ${already_run} ]]; then
	__usage__ 1
else
	[[ ${run_cflags} ]] && print_cflags
	[[ ${run_ldflags} ]] && print_ldflags
	[[ ${run_libs} ]] && print_libs
	# Need newline(\n) here
	echo
fi
