# Build the ULPatch documentation on github
name: DOC
on:
  push:
    paths:
      - 'docs/**'
      - 'docs/en/**'
      - 'docs/zh/**'
      - 'docs/images/**'
      - docs/requirements.txt
      - .github/workflows/docs.yml
      - mkdocs.yml
    branches:
      - master
  pull_request:
    paths:
      - 'docs/**'
      - 'docs/en/**'
      - 'docs/zh/**'
      - 'docs/images/**'
      - docs/requirements.txt
      - .github/workflows/docs.yml
      - mkdocs.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Build site
        run: mkdocs build
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && (github.repository == 'Rtoax/ulpatch' || github.repository == 'ulpatch/ulpatch')
        run: mkdocs gh-deploy --force

